examples/__init__.py, examples/benchmarking.py, examples/future_loading.py, examples/model_gen.py, examples/new_model.py, examples/noise.py, examples/sensitivity.py, examples/sim.py, examples/visualize.py, prog_model_template.py, setup.py, sphinx_config/conf.py, src/prog_models/__init__.py, src/prog_models/exceptions.py, src/prog_models/models/__init__.py, src/prog_models/models/battery_circuit.py, src/prog_models/models/battery_electrochem.py, src/prog_models/models/centrifugal_pump.py, src/prog_models/models/pneumatic_valve.py, src/prog_models/prognostics_model.py, src/prog_models/visualize.py, tests/__init__.py
Cosmetic and cleanup changes according to LGTM
=> cleanup LGTM recommendations

.lgtm.yml
Classifies some files as tests, documentation, examples for the LGMT static analysis tool. This will help with viewing the resulting analysis
=> Added LGMT Config File

.gitignore, examples/sim_pump.py, src/prog_models/models/__init__.py, src/prog_models/models/centrifugal_pump.py
The following improvements:
* Added example of using pump. 
* Fixed bug where pump event states were negative
* Split model into base and with wear
* Add .vscode to .gitignore
Closes #50
=> Pump Improvements

examples/future_loading.py, examples/new_model.py, examples/noise.py, prog_model_template.py, src/prog_models/models/battery_electrochem.py, src/prog_models/prognostics_model.py, tests/test_base_models.py, tests/test_examples.py
Noise is automatically generated in private functions __next_state and __output functions
=> Automatic Noise Generation

tests/__main__.py, tests/test_base_models.py, tests/test_battery.py, tests/test_centrifugal_pump.py, tests/test_examples.py, tests/test_pneumatic_valve.py
Add ability to execute tests individually
=> Individual Test Execution

examples/model_gen.py, examples/new_model.py, examples/sim.py, examples/sim_battery_eol.py, examples/sim_valve.py, src/prog_models/prognostics_model.py
Add option to print intermediately and use in examples
=> Intermediate Printing

examples/future_loading.py, examples/sim_valve.py, src/prog_models/models/battery_electrochem.py, src/prog_models/models/pneumatic_valve.py, src/prog_models/prognostics_model.py, src/prog_models/visualize.py, tests/__init__.py, tests/test_base_models.py, tests/test_battery.py
Resolve batch of issues from CodeFactor.io
=> CodeFactor

.github/workflows/python-package.yml
Now tests will confirm compatibility with prog_algs package. Both released (in master) and dev.
Closes #37
=> Add test of compatibility with prog_algs

src/prog_models/prognostics_model.py, tests/test_base_models.py
Added ability back to set the initial state in a simulation
=> New feature: set initial state in simulation

examples/__init__.py, examples/derived_params.py, prog_model_template.py, sphinx_config/getting_started.rst, src/prog_models/models/battery_electrochem.py, src/prog_models/prognostics_model.py, tests/test_base_models.py, tests/test_examples.py, tutorial.ipynb
* Updated Derived Parameter feature to use member dict instead of function. 
* Added new example
* Added feature to tutorial, template
* Added example to tests, documentation
=> Updates to Derived Param Feature

examples/sim_pump.py, src/prog_models/models/battery_electrochem.py, src/prog_models/models/centrifugal_pump.py, src/prog_models/models/pneumatic_valve.py
Fix the following issues:
1. Difference in indicies between x_0 and x_t (returned by dx, next_state)- could cause issue if used in a way where ordering matters 
2. rRadialdot should use x['rRadial'] instead of param['rRadial'] (in fact, rRadial param shouldn't exist)
3. rThrustdot shoudl be wThrust*rThrust*w^2
4. rThrust Param is unnecessary
=> Fix Various Issues identified by partner

sphinx_config/getting_started.rst
This is additional details beyond those present in the release notes.
=> Added detailed updates to docs

src/prog_models/prognostics_model.py
=> Removed unnecessary assignment

src/prog_models/prognostics_model.py
Resolving release review comment
=> Trivial renamed t -> t0

examples/__init__.py, examples/linear_model.py, src/prog_models/__init__.py, src/prog_models/linear_model.py
Implement a linear model abstract base class for models that can be described as a linear timeseries. Created an example demonstrating this
=> Implement Linear Model

.gitignore, tutorial.ipynb
Miscellaneous spelling/grammatical corrections in tutorial jupyter notebook doc.
=> Typo correction in tutorial.ipynb

.gitignore, src/prog_models/linear_model.py, src/prog_models/prognostics_model.py
Caching sizes of each significant array in PrognosticsModel and all children classes, refining how lengths of each array are obtained throughout the package.
=> Caching array sizes as class variables in PrognosticsModel

src/prog_models/sim_result.py, tests/test_sim_result.py
Testing SimResult's extend public method
=> Extending tests for SimResult

examples/__init__.py, examples/dataset.py, sphinx_config/getting_started.rst, src/prog_models/datasets/__init__.py, src/prog_models/datasets/nasa_battery.py, tests/test_examples.py
Closes #213 
Added submodule for datasets. As a first dataset implemented access to battery dataset. The data is restructured to a useful format. The format chosen was the following:
* description [dictionary]
* data: List[np.Array] of format [run_id][time_index][variable] - where each run is a rank-2 tensor. This format was selected because it's more or less the format expected in ML operations for time series. 
Also, added an example demonstrating how to use it. 
NOTE: This does not include a test, that's on purpose because it takes some time
Follow-up issues created #218, #217, #216, #215, #214
=> Battery Dataset

examples/matrix_model.py, src/prog_models/prognostics_model.py, src/prog_models/utils/containers.py, tests/__init__.py, tests/__main__.py, tests/test_base_models.py, tests/test_dict_like_matrix_wrapper.py, tests/test_examples.py
Created a container for input, states, outputs where data is stored as a matrix, but can be accessed and manipulated as either a dictionary or a matrix. 
Also added tests
Note: This change breaks vectorized behavior, so the example was removed and issue #236 was added to resolve this.
Follow up issues (i.e., next steps):
#232 
#233 
#235 
#234 
#236
=> Matrix Model Approach 2: Container

src/prog_models/utils/containers.py, tests/test_dict_like_matrix_wrapper.py
Update function will be needed by some of the existing models
=> Add update function to container

.github/workflows/python-package.yml, tests/__init__.py, tests/__main__.py, tests/test_tutorials.py
Testing to ensure successful execution of Jupyter notebook tutorial files.
=> Autotesting for Jupyter notebook tutorial files

src/prog_models/models/battery_circuit.py, src/prog_models/models/battery_electrochem.py, src/prog_models/models/centrifugal_pump.py, src/prog_models/models/pneumatic_valve.py, src/prog_models/models/thrown_object.py
also, cleaned up numpy imports and removed inf import.
=> Update existing models to use Matrix feature

src/prog_models/prognostics_model.py, src/prog_models/utils/containers.py
Fix a few bugs:
1. Cannot instantiate a Container from another
2. Deleting a key removes it from all future containers (fixed with copy)
3. Missing dt in application of process noise
=> Container and Process Noise Bugs

src/prog_models/datasets/nasa_battery.py, src/prog_models/datasets/nasa_cmapss.py, src/prog_models/linear_model.py, src/prog_models/models/battery_circuit.py, src/prog_models/models/battery_electrochem.py, src/prog_models/models/centrifugal_pump.py, src/prog_models/models/pneumatic_valve.py, src/prog_models/models/thrown_object.py, src/prog_models/prognostics_model.py, src/prog_models/sim_result.py, src/prog_models/utils/containers.py, src/prog_models/utils/noise_functions.py, src/prog_models/utils/parameters.py, src/prog_models/utils/progress_bar.py, src/prog_models/visualize.py
Use typing to provide better hints where appropriate.
=> Improved type hints

.gitignore, examples/derived_params.py, examples/state_limits.py, src/prog_models/models/thrown_object.py
=> Add drag to model

src/prog_models/sim_result.py, tests/test_sim_result.py
Given a single simulation result, for each event: go through all predicted states and compare those to the next one.
In SimResult, iterate self.data and use monotonicity formula to determine result.
=> Implement monotonicity for SimResult

src/prog_models/prognostics_model.py
Fixes 4 bugs:
1. vstack didn't work for an empty input
2. The eigen value calculation was hardcoded for battery (where there is 1 input)
3. threshold_keys and first_output aren't passed to simulate_to
4. Malformed F matrix
Also a few suggested changes
1. Move process noise tmp out of class definition (it doesn't have to be a class member)
2. Clean simulation
5. Remove config parameter defaults that are identical to simulate_to parameters
=> Bugfixes and suggested changes

src/prog_models/prognostics_model.py
Fixed issue where MSE wasn't actually normalized
=> Fixed MSE 

examples/generate_surrogate.py, sphinx_config/getting_started.rst, src/prog_models/prognostics_model.py, tests/__main__.py, tests/test_sim_result.py, tests/test_surrogates.py
Created tests for surrogate model. 
Also, added additional input validation
=> Surrogate Model Tests

src/prog_models/utils/parameters.py
Fix issue where, when the noise is set to 0, then away from 0- the dist stays at none if *_noise_dist key doesn't exist
=> Fix undefined dist

src/prog_models/prognostics_model.py
Tuple save freq (like that from Monte Carlo) were not handled correctly by surrogate models
=> fix tuple issue

src/prog_models/prognostics_model.py, src/prog_models/sim_result.py
Remove unnecessary deepcopies (copy would be fine)
=> Remove unnecessary deepcopies

src/prog_models/utils/containers.py
Fixed 2 issues with model.*containers:
1. They weren't being copied correctly
2. Equality wasn't working between a container and equivalent dict
=> Fixed issue with containers

src/prog_models/prognostics_model.py, src/prog_models/sim_result.py, src/prog_models/utils/containers.py
Includes:
* Removing unnecessary deepcopies
* Fixed initial state updating bug in simulate_to*
* Fix DMD handling of tuple save_freq
* Fix copy and comparison for DictLikeMatrixWrapper
=> hotfix v1.3.1

examples/sim.py, src/prog_models/prognostics_model.py, tests/test_base_models.py
Added RK4 integration method for simulate_to
=> Runge Kutta 4 Integration

src/prog_models/prognostics_model.py, src/prog_models/surrogates/__init__.py, src/prog_models/surrogates/dmd.py
Refactored surrogate to be its own subpackage `prog_models.surrogates`. 
m.generate_surrogate() now calls the constructor of the appropriate class in the new package. 
Adding new surrogate method can be done by creating a new class, and adding it to the lookup in __init__.py
Thoughts on the implementation?
=> Refactored Surrogate

.github/workflows/python-package.yml, src/prog_models/linear_model.py, src/prog_models/models/battery_circuit.py, src/prog_models/models/battery_electrochem.py, src/prog_models/models/centrifugal_pump.py, src/prog_models/models/esc.py, src/prog_models/models/pneumatic_valve.py, src/prog_models/models/thrown_object.py, src/prog_models/prognostics_model.py, src/prog_models/sim_result.py, src/prog_models/utils/containers.py, src/prog_models/utils/noise_functions.py, src/prog_models/utils/parameters.py, tests/benchmarking.py, tests/test_base_models.py
A few more optimizations and improvements, including:
* Updates to Noise to use matrix multiplication inplace (instead of forming a new dictionary)
* To support this, store process and measurement noise as *Container
* Update to SimResult to store vectorized input as 2d instead of 3d array
* Add atleast_1d commands in models to support above change (this is only needed in models that support vectorized input- advanced feature)
* Default next_state uses matrix multiplication if it can
* Extend benchmarking script
* Remove tests with released prog_algs (since that combo won't work)
Note: these changes will speed things up, but will require stricter adherence to using *Containers instead of dictionaries
Note2: This is related to a similar PR in prog_algs …
=> Additional Optimizations

examples/custom_model.py, examples/full_lstm_model.py, examples/lstm_model.py, src/prog_models/data_models/__init__.py, src/prog_models/data_models/data_model.py, src/prog_models/data_models/lstm_model.py, tests/test_lstm.py
Refactored LSTM into a subpackage data_models, and added abstract base class DataModel. 
Also, set default noise to 0
This is in anticipation of future data-driven models, and adding general tools. The change formalizes the interface. Future changes will also bring in DMD Model as a subclass
=> Refactored lstm 

examples/sim_pump.py, examples/visualize.py
Fixing old implemented code to new implementation style
=> sim_pump plot bug fixed

tests/test_tutorials.py
only run if testbook is installed - otherwise warn
=> Updated Testbook Test

tests/test_data_model.py
Added a Try and Except Statement that outputs a warning if pickle doesn't work with users particular system
=> LSTM Pickle FileNotFound Error

examples/sim_dcmotor_singlephase.py, src/prog_models/models/dcmotor_singlephase.py
There are a couple of things that should be addressed:
- Inductance L is probably too high.
- Some comments refer to the particular DC motor parameters we used from KDE Direct website, and do not really apply to other motors, so should be deleted.
=> adding dcmotor_singlephase model and corresponding example

examples/sim.py, src/prog_models/models/battery_electrochem.py, tests/test_data_model.py
Adds new performance metric i_max, which is the current that would cause the steady state voltage to pass below VEOD. Updates the example to use this metric. 
Also, cached additional parameters as an optimization
=> Battery Performance Metric

src/prog_models/data_models/lstm_model.py
Put the validation metrics (e.g., loss mae) on same chart as the training metrics
=> Put validation metrics on same chart

examples/dataset.py, src/prog_models/datasets/nasa_battery.py, tests/test_datasets.py
Fix the battery datasets to use the right links. Also fix the example to conform with some changes made earlier in the year that weren't able to be tested until this point.
=> Fix dataset and example

src/prog_models/models/dcmotor_singlephase.py
Small changes to how inertia is communicated/represented in the DC Single Phase Motor Model.
=> Slight Changes to Inertia in DC Single Phase

src/prog_models/prognostics_model.py, src/prog_models/utils/parameters.py, src/prog_models/utils/serialization.py
Move class and function used in JSON serialization to separate util file. Added functionality to parameters directly as well. 
This change helps enable some features in prog_server
=> Updates to serialization

requirements.txt, setup.py, src/prog_models/__init__.py
fixing the intel-mac version issue.
=> fixing bug

src/prog_models/data_models/lstm_model.py
Removing np.float which is removed in numpy 1.24
=> np.float -> float64

examples/__init__.py, examples/ensemble.py, src/prog_models/__init__.py, src/prog_models/ensemble_model.py, tests/test_examples.py, tests/test_manual.py
Creates a new "Ensemble model" that combines one or more models. Each model is executed individually and the results are aggregated using the configurable aggregation method. 
This change also creates an example the example has 3 parts:
1. Ensemble model of 3 BatteryCircuit models with different configuration. The third is very wrong (outlier). The result is wildly inaccurate as a result. 
2. The same model with a median aggregation method. The median aggregation will eliminate the outlier, leading to good performance. 
3. A new ensemble model with members: BatteryCircuit and BatteryElectroChem, demonstration heterogeneous ensemble model. The two models have the same outputs but different states (except for one- battery temperature).
=> Ensemble Model (Closes #431)

examples/future_loading.py, src/prog_models/loading.py
Adds classes for complex future loading behavior (e.g., noise or moving average). 
Updated futureloading example
=> Added future loading classes

examples/composite_model.py, src/prog_models/__init__.py, src/prog_models/composite_model.py, src/prog_models/models/test_models/linear_models.py, src/prog_models/utils/containers.py, tests/test_base_models.py
Creates CompositeModel class, a class used to create a model of a system of inter-related systems, where the outputs or states of one are the input to another. The resulting composite model is a fully-functional prognostic model.
Also includes an example of its use, and tests. Adds the following additional features:
* OneInputOneOutputNoEventLM test model
* Container.get which works the same as dict.get
=> Composite Model

src/prog_models/data_models/lstm_model.py
Fix issue where LSTM breaks with no inputs
=> Fix LSTM Bug

src/prog_models/prognostics_model.py, tests/test_base_models.py
Added is_continuous and is_discrete properties
=> Added is_continuous/discrete

src/prog_models/linear_model.py
Moved setter method in the linear_model.py file for parameter E to make code more clear.
=> Fixed import and moved setter methods to correct location

src/prog_models/prognostics_model.py
the example comment was not correct. I tried running every model and the return didn't match any of them.
=> updated example and imports

setup.py, src/prog_models/__init__.py, src/prog_models/prognostics_model.py
This hot fix fixes an issue with the Parameter Estimation feature. Parameter estimation wasn't working correctly. Issue and solution were identified by @kjjarvis
=> Hotfix v1.4.6

.github/workflows/python-package.yml, src/prog_models/ensemble_model.py, src/prog_models/models/test_models/linear_models.py, tests/__main__.py, tests/test_ensemble.py
This PR introduces a set of tests for the ensemble model feature
=> Improve Ensemble Tests

src/prog_models/utils/calc_error.py
Add a few comments describing the mysterious none check and a general file description
=> Add comments and clean

src/prog_models/utils/containers.py
Corrected code that was creating a 3d array in self.matrix
=> Prog models feature/container none correction

examples/linear_model.py, src/prog_models/linear_model.py, src/prog_models/prognostics_model.py, src/prog_models/utils/calc_error.py, src/prog_models/utils/containers.py
Fixing exception and warnings messages as well as reformatting function parameters and documentation.
=> calc_error.py housekeeping

src/prog_models/sim_result.py, src/prog_models/utils/containers.py, tests/test_surrogates.py
Adds additional Deprecation Warnings for features present in Series that are not present in the current container. Also adds equals and dot functions. These are functions that we will expect users to start using in v1.6. Adding them now allows users to start updating their code to use these functions between the v1.5 and 1.6 releases
=> Additional Deprecation Warnings in *Container

src/prog_models/prognostics_model.py, src/prog_models/utils/next_state.py, src/prog_models/utils/parameters.py, tests/test_base_models.py
Allow any scipy integrator to be passed into integration_method parameter
=> Scipy integrator

src/prog_models/__init__.py, src/prog_models/data_models/dmd.py, src/prog_models/datasets/nasa_cmapss.py, src/prog_models/exceptions.py, src/prog_models/prognostics_model.py, src/prog_models/utils/containers.py, src/prog_models/utils/parameters.py, tests/test_base_models.py, tests/test_dict_like_matrix_wrapper.py, tests/test_surrogates.py
Update exceptions to use default python exceptions
=> Updated exceptions

examples/uav_dynamics_model.py, src/prog_models/loading/controllers.py, src/prog_models/models/aircraft_model/small_rotorcraft.py, src/prog_models/utils/traj_gen/trajectory.py
Update time to use float instead of date time. 
Also, small changes such as:
1.  Moved function to standalone instead of method
2. Removed eta_unix waypoint property
3. Removed vehicle model from use in Trajectory
4. Other cleanup
=> Float time

prog_model_template.py
Add Time of Event and Performance Metrics to Template
=> Add toe and p_met

src/prog_models/models/aircraft_model/vehicles/vehicles.py, src/prog_models/utils/traj_gen/trajectory.py
* Same math improvements
* Cleaning up spacing 
* fix warnings:
* print -> warn
* raise Warning -> warn
=> A few small suggested changes

tests/test_uav_model.py
Small syntax error in testing uav model is now fixed
=> Fixing uav_test

prog_model_template.py, src/prog_models/data_models/data_model.py, src/prog_models/prognostics_model.py, src/prog_models/utils/containers.py, src/prog_models/utils/next_state.py, src/prog_models/visualize.py
Finished doctests, fixed tuple bug in next_state.py
=> Prog models features/check doctests

src/prog_models/sim_result.py
Fixed the version comments. There were some missing.
=> fixed some version comments
