examples/__init__.py
examples/sim_battery_eol.py
sphinx_config/getting_started.rst
src/prog_models/models/battery_electrochem.py
tests/test_examples.py

See #43 
Battery EOD model becomes unstable when using SOC to maintain battery change (when simulating to EOD). There are cases where SOC as calculated is >0 but EOD has been met, leading to the above approach simulating past EOD. 
We have never run into this in the past as we've never used SOC to regulate future loading

Fix bug in SOC Calculation

---

src/prog_models/prognostics_model.py

Save time as an array (instead of list). Slightly faster- but limits type of time to double

Save time as array in sim

---

src/prog_models/prognostics_model.py
src/prog_models/sim_result.py
tests/__main__.py
tests/test_sim_result.py
tutorial.ipynb

This PR implements the Prediction Result class - adding capabilities to what is returned from a simulation. 
@jason-watkins, @wlamberson1: This goes against your suggestion. I tried implementing both and found this version with significantly cleaner and easier to use. This can also be extendable to analysis tools/operations comparisons (e.g., diff_outputs = output1 - outputs2). Since this is a research rather than an tool for deployment, I selected the easier to use/more expandable option accepting the inefficiency of duplicate storages of time.
I would still like your input on this implementation

Implement Prediction Result

---

src/prog_models/models/pneumatic_valve.py
src/prog_models/sim_result.py

Fixed 2 alerts:
1. Unnecessary condition in if/else (no other state was possible
2. __eq__ not overwritten (this is not necessary as the comparison is identical to it's parent class

Fixed 2 LGTM alerts

---

examples/state_limits.py
src/prog_models/prognostics_model.py
tests/test_base_models.py
tutorial.ipynb

v1.1 added the state bounding feature. There is some user interest in creating a separate function to apply bounds (. apply_limits(state) -> state) that is called from within __next_state(). This would enable other methods that externally agitate state (e.g., particle filters) to ensure they remain within bounds.

Moved limit checking into function

---

examples/__init__.py
examples/dynamic_step_size.py
sphinx_config/getting_started.rst
src/prog_models/prognostics_model.py
tests/test_base_models.py
tests/test_examples.py

Allows user to specify a function f(t, x) -> dt that specifies the next step.
This enables use case where step sizes are dynamic (i.e., a function of time or state). For example: step size my decrease as you approach an event state

Added Dynamic step size feature

---

examples/derived_params.py
examples/dynamic_step_size.py
examples/future_loading.py
examples/new_model.py
examples/noise.py
examples/param_est.py
examples/sensitivity.py
examples/state_limits.py
examples/visualize.py
src/prog_models/models/thrown_object.py

Problem: Some examples cannot be run alone as scripts because they're dependent on other examples. Since it's setup as a package imports have to be `from .[file_name] import [thing]` in order to support `python -m examples.[file_name]`. However, this breaks when you run a file by itself from within examples directory (e.g., press run in IDE). For that to work the command `from [file_name] import [thing]` is needed (without the period). Multiple users have had issues with this
Solution: remove the intra-package dependency by adding thrown_object to prog_models.models. Set it up to not be imported by default (not part of __init__.__all__), and update the examples to use this version instead of the version defined in examples.new_model
Closes #137

Decouple Thrown Object from Examples

---

examples/derived_params.py

Hi,
I noticed this typo while reading examples.
Kind regards,

Fix typo in derived_params example

---

examples/benchmarking.py
examples/dynamic_step_size.py
examples/future_loading.py
examples/model_gen.py
examples/new_model.py
examples/noise.py
examples/sensitivity.py
examples/sim.py
examples/sim_battery_eol.py
examples/state_limits.py
examples/vectorized.py
examples/visualize.py
prog_model_template.py
src/prog_models/models/battery_circuit.py
src/prog_models/models/battery_electrochem.py
src/prog_models/models/thrown_object.py
src/prog_models/prognostics_model.py
tests/test_base_models.py
tutorial.ipynb

Make initial output and input optional for some models, propagate changes to simulate_to and examples. 
For models that dont use output to estimate initial state, we shouldn't have to supply it. 
This enables using default first state in simulation. A feature requested in PaaS

Make initial output and input optional in initialize

---

src/prog_models/sim_result.py

Fixed bug where LazySimResult wasn't creating new states or times arrays. Showed up when extending

Fix  bug in LazySimResult

---

src/prog_models/prognostics_model.py
tests/test_base_models.py

Add ability to compare models using equality test (e.g, m1 == m2). Returns true if class type (e.g., BatteryCircuit or ThrownObject) and all configuration params are the same. 
Updated the pickle test to use equality comparison

Add equality comparison for models

---

src/prog_models/prognostics_model.py

Rename observables to performance metrics while maintaining backwards compatibility

Rename observables to performance metrics

---

src/prog_models/models/battery_electrochem.py
src/prog_models/models/centrifugal_pump.py
src/prog_models/models/pneumatic_valve.py
tests/test_battery.py
tests/test_centrifugal_pump.py
tests/test_pneumatic_valve.py

Some parameters are overwritten in model extensions, adding warning that notifies user if they're setting a parameter for which this is true.
Also, removed 2 parameters that were unnecessarily being set in output method

Add warning when setting param that will be overwritten

---

.gitignore
src/prog_models/sim_result.py
tests/test_sim_result.py

Introducing unittesting and bug fixes to correct LazySimResult not being pickle-able due to its function member variable.

Bug fix for LazySimResult not being pickle-able

---

src/prog_models/sim_result.py
tests/test_sim_result.py

LazySimResult method to convert current object to a SimResult object

Implementation of LazySimResult to_SimResult() method

---

src/prog_models/sim_result.py
tests/test_sim_result.py

Enable SimResult to be extended by LazySimResult.
If possible, extend LazySimResult with SimResult. If not, add check to prevent trying.

Implementation of LazySimResult extending a SimResult object

---

examples/events.py
examples/future_loading.py
examples/model_gen.py
examples/new_model.py
examples/noise.py
examples/sensitivity.py
examples/sim_pump.py
examples/state_limits.py
examples/visualize.py
src/prog_models/prognostics_model.py
tests/test_base_models.py
tests/test_battery.py
tests/test_centrifugal_pump.py
tests/test_pneumatic_valve.py
tests/test_sim_result.py
tutorial.ipynb

Implementing change for simulate_to* methods in prog_models/prognostics_model.py to return namedtuples instead of basic tuples. Motivation for change is ease of readability and access to objects in the return from the method's result.

Feature for simulate_to* to return namedtuples instead of basic tuples

---

src/prog_models/sim_result.py

Comment informing user that the fcn of both LazySimResult objects must be the same if they are to extend the other

Adding comment to LazySimResult describing fcn MUST be the same

---

src/prog_models/prognostics_model.py
src/prog_models/utils/containers.py
tests/test_examples.py

vectorized models were not working in the current implementation. This is because .item() which converts from np.float64 -> float doesn't work when the element is an ndarray. 
Solution: Dont convert. Users have to use np.float64.
Also, refactored prog_models initializer to use __set_state__, because when copying a prog_model it wasn't running the noise logic. Happily this removed duplicated lines of code!
Fixed the progmodel parameters class from only running the noise logic when changing the noise parameter, but not the noise dict parameter

Fixed behavior for vectorized models

---

examples/linear_model.py
src/prog_models/linear_model.py
tests/test_base_models.py

Implement the matrix feature in linear model. This removes the need for conversion, speeding up simulation. 
Also required changes in the example and tests.

Propagate Matrix work to linear model

---

src/prog_models/prognostics_model.py

Issue: In monte carlo predictions we run multiple simulations from different points. The problem with this is that the save_pts don't align anymore when using save frequency. 
Solution, allow for the specification of the starting time for the save frequency. When starting time is specified, that will be used to start the sequence instead of the initial time in simulation.

Fix times alignment

---

src/prog_models/prognostics_model.py
tests/test_centrifugal_pump.py

This PR is to respond to something @kjjarvis brought up related to the estimation of input from an input function in simulation.
Simulation works by incrementing the state forward with time. Some current state (x_t), a time interval, and an estimation of the input (i.e., loading) during the interval are used to estimate the next state (x_t+1). The current approach is to get the input at the next state and use that as the load for the interval. The problem is that input can be continuous, so this approach is not always an accurate representation of the load during the interval.
Our suggested solution is to use the load at the midpoint between time t and t+1 to represent the load for the interval. This would be a better representation in most cases.

Update load calculation at midpoint

---

src/prog_models/models/battery_circuit.py
src/prog_models/models/battery_electrochem.py

Battery circuit event state called output- this breaks down any ability to subclass the battery circuit with different outputs, because of the outputcontainer filtering feature. 
I break this interdependence by duplicating the code.

fix battery circuit dependency

---

examples/sim.py
src/prog_models/prognostics_model.py
tests/test_base_models.py

Add feature where step size can be determined automatically to capture save_pts and save_freq. This will later support using the step size in the future load as the sim step size. 
Now when setting dt you have the following options:
* Number - constant dt step size
* Function (t, x) -> dt - step size by function
* string - step size mode ('auto' or 'constant').
* constant is equivalent to dt=1.0
* auto will set the dt to capture any save pts and save_freq perfectly, and later the future_loading
* tuple (mode, dt)
* ('constant', dt) - is equivalent to dt=dt
* ('auto', dt) - sets step size automatically with an upper limit of dt. 
Set default as auto with maximum step size of 1.0.

Automatic step size

---

src/prog_models/datasets/nasa_battery.py
src/prog_models/datasets/nasa_cmapss.py
tests/test_datasets.py

The website is currently down, and NASA had it forward to a different site. This wasn't caught by our check and the feature gave a weird error. 
This update will catch the issue and give an accurate error.

Exception when dataset has moved

---

src/prog_models/surrogates/dmd.py

Surrogate method next_state had matrix dimension issues for the case when there were no inputs

Fix x.matrix size issue in next_state

---

examples/custom_model.py
examples/full_lstm_model.py
examples/lstm_model.py
src/prog_models/data_models/data_model.py
src/prog_models/data_models/lstm_model.py
src/prog_models/prognostics_model.py
src/prog_models/utils/containers.py
tests/test_base_models.py
tests/test_lstm.py

Added from_model class method to DataModel. This will now allow users to create models from others (i.e., surrogates) for any data model class. It essentially generates data from the original model, and then calls the from_data method.
* Split data into inputs, outputs, states, and event_states. This allows model classes to all accept the data they need (e.g., DMD needs all these, but LSTM only needs the first 2). Any additional information received will be ignored
* Renamed the previous inputs, outputs, etc. to input_keys, output_keys, etc. This is to not conflict with the inputs/outputs from the above bullet
* Added a few additional input validation checks into LSTMStateTransitionModel.from_data
* Moved PrognosticsModel.events to be object member instead of class member. This is to …

Add DataModel.from_model

---

src/prog_models/data_models/data_model.py
src/prog_models/data_models/dmd.py
src/prog_models/data_models/lstm_model.py
src/prog_models/prognostics_model.py
tests/test_data_model.py

This PR will ensure that DataModels (e.g., LSTM and DMD) can be pickeled and restored. To do so we define the __setstate__ and __getstate__ methods which are called to get the configuration and configure the constructed object. We also define the __getnewargs__ method, which defines the arguments for the __new__ method, when defined. 
To do this, I also had to make DMD matrix an attribute of the DMD class
Also, in DMD.__init__, reordered params building and input checking to make the exception if you give incorrect input a TINY bit faster

Make DataModels Pickle-able

---

src/prog_models/data_models/dmd.py
tests/test_data_model.py

DMD was supposed to "infer" dt from the data if not provided. 
This functionality was broken (simple typo). I suspect that block of code was somewhere else in a previous version, then was moved without updating the variable
Also added a test to catch this in the future

Fix dmd without dt

---

scripts/test_copyright.py

Fix issue where our copyright testing script missed some python files with alternate file extensions (e.g., .pyw or .py3) and checked files that did not require copyright statement (e.g., .npy). 
Issue first identified by user @snoyes in #390

Fix test copyright

---

examples/lstm_model.py
src/prog_models/data_models/lstm_model.py
src/prog_models/prognostics_model.py
tests/test_data_model.py

Implement Early Stopping for LSTM Model. 
This feature, described here: https://keras.io/api/callbacks/early_stopping/, will stop the training of the epoch once it reaches certain conditions. Conditions can be configured using the early_stop.cfg parameter. 
Feature is tested by running two runs. One with early stopping, and one without. Then I parse the output to see how many epochs were run. For early stopping it should be less than the maximum.
Also, added note to example, explaining this

Early stopping

---

examples/lstm_model.py
src/prog_models/data_models/lstm_model.py
tests/test_data_model.py

Split the LSTM model into 2 parts (state_model and output_model), in anticipation of future iterations that will also learn relationship with event_state, thresholds_met, etc. 
Designed in such a way as to still allow passing in one model, if desired.

Update LSTM to split model

---

examples/custom_model.py
examples/lstm_model.py
src/prog_models/data_models/data_model.py
src/prog_models/data_models/lstm_model.py
src/prog_models/utils/parameters.py

Extending the divided LSTM model introduced in #395 to include estimation of threshold_met and event_state. Each of these are optional, only working if the relevant data is provided. 
Event_state is just like outputs, but thresholdmet is calculated using softmax (since it's a classification problem). 
Example for battery was extended to include this. 
[Presentation1.pdf](https://github.com/nasa/prog_models/files/9568311/Presentation1.pdf)

Extending LSTM to include event_states, thresh_met

---

src/prog_models/data_models/lstm_model.py
tests/test_data_model.py

The LSTM model was performing poorly, resulting in poor test performance, like that shown below (right is LSTM, left is original)
Investigation of this fault identified a few issues, some with the tests, others with the actual functionality. 
1. LSTM preprocessing wasn't using all the data. It was missing one datapoint for each run
2. LSTM preprocessing wasn't calculating the output window correctly (z_ii) for appending to u.
3. Tests - Training just had one run, and part of it was used for validation, so the training data was incomplete. To fix this I duplicated the data. Not good practice, but it was ok for the test. 
I also increased the default number of epochs. The default was unreasonably low.

A few LSTM Bugfixes

---

src/prog_models/prognostics_model.py
tests/test_serialization.py

The custom encoder for serializing parameters in prognostics_model was missing a pickle import. Added pickle import. Also changed copyright date in test_serialization.

Add missing pickle import to custom encoder

---

src/prog_models/data_models/dmd.py
src/prog_models/data_models/lstm_model.py
src/prog_models/prognostics_model.py

This PR includes various bug fixes. Specifically:
* Update DMD Model to support overwritten threshold_met equation (used in ASO project). For example, if you have a definition of threshold_met as a function of the outputs, rather than learning that relationship, you can define it by overriding threshold_met
* LSTM Model- added exception if you do not provide enough data to fill the window. E.g., if you provide a time series of length 10 to learn a model with a window of 20. 
* LSTM Model - updated default dt to be positive. Before it was 0- which means it would never move forward
* LSTM model - Added exception in simulate_to_threshold if you're not simulating far enough forward to fill the window. E.g., if you have a window size of 20, but are only simulating 10 steps
* Prognostics Model …

Various bug fixes to the data model

---

src/prog_models/prognostics_model.py

When serializing a model, if the custom encoder received a numpy.bool_ value, it pickled the result. We've now added a reconfiguration of these numpy.bool_ values to be standard bool values, which are supported by JSON so no pickling is required.

Reconfigure numpy bool in serialization encoder

---

src/prog_models/prognostics_model.py
tests/test_base_models.py

This PR updates behavior if event state or threshold_met is not provided:
* If event_state is not overridden, but threshold_met is: Will return event_state of 0 if threshold_met is True, else 1
* if threshold_met is overridden, but event_state is not: Will return threshold_met of True if event_state is 0, else False
* if neither are overridden: Will return empty dict (i.e., no events).

Make Event State equation optional

---

src/prog_models/datasets/nasa_battery.py
src/prog_models/datasets/nasa_cmapss.py
tests/test_datasets.py

Fix issues with datasets, specifically:
* Update CMAPSS link. 
* Remove Battery data download. Currently battery data is only available on PHM Society's website, and they have the full dataset as one file. I'm going to upload them as split files to data.nasa.gov soon, and will add this functionality back when that's done
* Also removed the associated tests

Fix issues with datasets

---

src/prog_models/models/battery_circuit.py

There are two base battery models: ElectroChemical and Circuit. They are intended to be interchangeable with each other, each have advantages over the other (ElectroChem is more accurate and complete, circuit is faster) and therefore used in different cases.
However, in practice they are not because the Circuit expects temperature in °C, whereas the electrochem expects Kelvin. To fix this I've changed the Circuit model to also use kelvin. 
This issue came up when testing the new EnsembleModel feature.

Switch circuit model to use kelvin

---

README.md
setup.py
src/prog_models/__init__.py
src/prog_models/prognostics_model.py
src/prog_models/utils/containers.py
tests/test_base_models.py

Fix issue with Measurement Noise in LazySimResult. When using LazySimResult, noise is not added to the output. Issue first identified here: https://github.com/nasa/prog_algs/issues/220. A test was added to ensure this continues working
Also, updated one of the error messages.

Hotfix v1.4.4

---

setup.py
src/prog_models/__init__.py
src/prog_models/models/experimental/__init__.py
src/prog_models/prognostics_model.py
tests/test_surrogates.py

This PR fixes an issue in DMD where 1e99 was appended to the end of save_pts, breaking this feature. 
The issue was originating from python's way of using references for objects. 1e99 was appended inside simulate_to_threshold, making the same change in kwargs, which effected the behavior in the larger scope of DMD. 
The fix moves away from appending 1e99 in favor of adding an additional check.
Bug was found by @kjjarvis 
Also added missing copyright

hotfix v1.4.5: Fix save pt behavior 

---

src/prog_models/models/pneumatic_valve.py
tests/test_base_models.py
tests/test_pneumatic_valve.py

This hotfix resolves a few compatibility issues related to the behavior of arrays in numpy v1.24.0 (identified in rc2). Specifically:
* Remove test for behavior of uneven array. Numpy now automatically raises an exception
* Remove vectorization of pneumatic valve. The gas flow equation no longer works correctly with vectorized states. 
Thank you @kjjarvis for identifying and helping to resolve these bugs.

hotfix v1.4.5c Numpy compatability issues

---

examples/direct_model.py
src/prog_models/prognostics_model.py
tests/__main__.py
tests/test_base_models.py
tests/test_direct.py

This PR introduces the concept of a "Direct Model". Direct models map from state to time of event directly without having to perform state transition.
Direct models are introduced through a new method time_of_event which returns the time of event for each event as a dictionary. For direct models this function is overwritten.
When this function is not overwritten-simulate to threshold is called to estimate this value using simulation. 
The pr also includes an example, which calls time of event for direct model and non-direct model. This PR also introduces a is_direct_model property which returns true if time_of_event is overwritten. Tests were also added for both a direct model inherited from a state transition model and one that isn't.
In order to support simple direct models, I had to …

Direct Model Interface

---

examples/composite_model.py
src/prog_models/models/__init__.py
src/prog_models/models/propeller_load.py
tests/test_powertrain.py

Very Simple PR. I just moved the propeller load model from the composite example to the prog_models.models package (Implements ticket #478, idea by kjjarvis)

[Simple] Move Propeller Load Model

---

src/prog_models/prognostics_model.py
src/prog_models/utils/parameters.py
src/prog_models/utils/size.py
tests/test_base_models.py

This is useful for benchmarking and requested by the TechEdSat effort. Now sys.getsizeof works properly for PrognosticsModels and Parameters. 
I added two tests that show that adding to the model increases the size by the expected amount. This is challenging because the size of overhead is python version and computer-dependent. To handle this the tests pass so long as the overhead is "reasonable".
This change also includes changing the default in parameters to "not copy" this allows python's optimizations to stay in place. I originally changed this to allow for test of repeated objects in parameters, but it is also a good change generally. 
This implements the first part of #493. __sizeof__ wasn't implemented for the containers (SimResult, SimResults, and *Containers) because they will …

Add ability to estimate the size of a model 

---

tests/__main__.py

The serialization tests were not included in the __main__ script for the tests. This has been fixed.

Adding serialization tests to __main__ for tests

---

src/prog_models/prognostics_model.py
src/prog_models/utils/next_state.py

Small first step towards cleaning up prognostics_model.py. This change moves the state transition wrappers for different integration methods out of prognostics_model.py and into its own file
This change will also help support additional integration methods being worked on by partners.

Move next_state into utils

---

tests/__main__.py
tests/test_base_models.py

This PR makes 2 test-related changes:
* Cleans up test_base_models to use "using self.assertRaises" 
* Removes the benchmarking in test all (this is done separately)

Cleanup test_base_models and remove benchmarking

---

src/prog_models/utils/calc_error.py

When passing in a dictionary to keyword argument 'x0' in any of our given subroutine error methods in calc_error, we are incorrectly transferring the datatype from a dictionary to a StateContainer.

Fixing how to initialize StateContainer

---

src/prog_models/utils/noise_functions.py

Update noise functions to apply noise inplace instead of creating a new object. The result is that this operation will be quicker

Inplace noise

---

src/prog_models/composite_model.py
tests/test_composite.py

Extend composite to allow connections from Performance Metrics. This allows the input of one model to be connected to the performance metric from another.
https://github.com/nasa/prog_models/issues/487

487 Composite: pm connections

---

examples/events.py
examples/future_loading.py
examples/sim.py
src/prog_models/loading.py
src/prog_models/prognostics_model.py
tests/test_battery.py

Two related changes:
1. Added a new loading scheme that defines the logic for piecewise loading profiles
2. Added "stop points". These are points where the simulation will be sure to stop if using "auto" dt. This is important if there are point in the loading profile that you want to capture
3. Will automatically grab the inflection points of the piecewise scheme as stop points (if using "auto" dt)

314 Auto step for piecewise loading profile

---

src/prog_models/data_models/lstm_model.py

Update TF to be imported lazily (only if using LSTM from_data). This will not be used by most users, so this speeds up importing prog_models

lazy import

---

tests/test_examples.py

This PR addresses a bug in using the 'mock' attribute of unittest by explicitly importing mock in each test that uses this

Adding explicit import of mock.patch as bugfix

---

src/prog_models/loading/gaussian_wrapper.py
src/prog_models/prognostics_model.py
src/prog_models/utils/parameters.py

abstract base classes in typing are deprecated. Switching to collections.abc.

Switch from Typing to collections.abc

---

src/prog_models/sim_result.py

A few suggested changes:
* Remove duplicate import of warn
* Reorder imports to be in alphabetical (reduces likelihood of future duplicate imports)
* Move to using collections.abc.Callable (typing.Callable deprecated by python)
* Fix __delitem__ (super had extra argument)
* Remove double drop from .pop (was dropped in pop and also pop_by_index, caused error).
* Newline between methods

Simresult suggestions

---

tutorial.ipynb

Cleaning up small details of tutorial, e.g. typos; added a sentence on serializing entire models as well as a note of using different error methods for calc_error

Update tutorial - add serialization and calc_error notes 
